services:
  dev:
    build: .
    image: med_rob_project:latest
    container_name: med_rob_dev
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash

